name: LearningHub CI/CD

on:
  push:
    branches:
      - main

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Show Files
        run: ls


      - name: Docker Compose Validate
        run: docker compose config


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/learninghub-frontend ./LearningHub_Vellaration


      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/learninghub-frontend


      - name: Build Backend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/learninghub-backend ./LearningHub_Backend


      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/learninghub-backend